baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
sectionPagesMenu = "main"


[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'This is the blog section'
  title = 'blog section'
  url = '/blog/'
  weight = -110

[[menu.main]]
  identifier = 'asdf'
  name = 'This is the asdf section'
  title = 'asdf section'
  url = '/asdf/'
  weight = -110

[[menu.main]]
  identifier = 'qwer'
  name = 'This is the qwer section'
  title = 'qwer section'
  url = '/qwer/'
  weight = -110
  parent = "main"
