baseURL = 'https://v01-hugo.pages.dev/'
languageCode = 'en-us'
title = 'Klaus Breyer, a CTO writing about Code, Architecture & Engineering Orgs'
copyright = 'Klaus Breyer'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true

[params]
  author = 'Klaus Breyer'
  description = "A CTO writing about Code, Architecture & Engineering Orgs"

[menu]
# [[menu.main]]
#   identifier = 'Home'
#   name = 'Home'
# #   title = 'Home'
#   url = '/'
#   weight = -1000

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
