baseURL = 'https://v01-hugo.pages.dev/'
languageCode = 'en-us'
title = 'Klaus Breyer, a CTO writing about Code, Business, Product & Engineering Orgs'
copyright = 'Klaus Breyer'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true
enableRobotsTXT = true

[author]
  name = 'Klaus Breyer'

[sitemap]
  changefreq = 'monthly'


[social]
  twitter = 'klausbreyer'

[params]
  repo = "https://github.com/klausbreyer/v01.io/blob/main/content/"
  description = 'I have been responsible for technology and teams since I founded my first startup in 2010, right after graduating in Software Engineering. Since then, I have been actively or consultatively involved in several other companies as CTO and CPO. I have built, managed, and launched many individual technical projects in (a constantly changing) modern web stack: From fast-moving independent startup projects to brownfield microservice environments. '
  image = 'images/klaus-breyer.jpg'
  title = 'Klaus Breyer, a CTO writing about Code, Business, Product & Engineering Orgs'


# [menu]
# [[menu.main]]
#   name = 'Open Source'
#   url = '/categories/open-source/'
#   weight = 100

# [[menu.main]]
#   name = 'unixtime.app'
#   url = '/categories/unixtime.app/'
#   weight = 110

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
