baseURL = 'https://www.v01.io/'
languageCode = 'en-us'
title = 'Klaus Breyer – Independent CTO / Code, Architecture & Engineering Org'
sectionPagesMenu = "main"
preserveTaxonomyNames = true

[menu]
[[menu.main]]
  identifier = 'Home'
  name = 'Home'
#   title = 'Home'
  url = '/'
  weight = -1000

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
