baseURL = 'https://www.v01.io/'
title = 'Klaus Breyer > CTO writing about Code, Business, Product & Engineering Orgs.'
copyright = 'Klaus Breyer'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true
enableRobotsTXT = true

languageCode = 'en'
defaultContentLanguage = 'en'
[languages]
  [languages.de]
  [languages.en]



[author]
  name = 'Klaus Breyer'

[sitemap]
  changefreq = 'monthly'


[social]
  twitter = 'klausbreyer'

[params]
  repo = "https://github.com/klausbreyer/v01.io/blob/main/content/"
  description = "I'm Klaus Breyer, a seasoned technology leader and entrepreneur with a degree in Software Engineering. Over the past decade, I've led high-performing teams, founded multiple startups, and played pivotal roles in the success of several other companies as their CTO or CPTO. I'm a big believer in Shape Up and have led numerous cutting-edge projects. My leadership philosophy is centered around building strong technical and organizational infrastructures that empower individuals to do their best work."
  image = 'images/klaus-breyer.jpg'
  title = 'Klaus Breyer > CTO writing about Code, Business, Product & Engineering Orgs.'

[privacy]
  [privacy.youtube]
    privacyEnhanced = true


[menu]
[[menu.main]]
  name = 'Blog'
  url = '/posts/'
  weight = 10

[[menu.main]]
  name = 'Appearances'
  url = '/pages/appearances/'
  weight = 20

[[menu.main]]
  name = 'Bookshelf'
  url = '/pages/bookshelf/'
  weight = 30

[[menu.main]]
  name = 'Consulting'
  url = '/pages/consulting/'
  weight = 40

[[menu.main]]
  name = 'Shape Up'
  url = '/pages/shape-up/'
  weight = 50

[[menu.main]]
  name = 'Funding'
  url = '/pages/funding/'
  weight = 60

# [[menu.main]]
#   name = 'unixtime.app'
#   url = '/categories/unixtime.app/'
#   weight = 110

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
