baseURL = 'https://v01-hugo.pages.dev/'
languageCode = 'en-us'
title = 'Klaus Breyer, a CTO writing about Code, Architecture & Engineering Orgs'
copyright = 'Klaus Breyer'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true

[params]
  author = 'Klaus Breyer'
  description = "A CTO writing about Code, Architecture & Engineering Orgs"

[menu]
# [[menu.main]]
#   name = 'Open Source'
#   url = '/categories/open-source/'
#   weight = 40

# [[menu.main]]
#   name = 'unixtime.app'
#   url = '/categories/unixtime.app/'
#   weight = 50

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
