baseURL = 'https://v01-hugo.pages.dev/'
languageCode = 'en-us'
title = 'Klaus Breyer, a CTO writing about Code, Architecture & Engineering Orgs'
copyright = 'Klaus Breyer'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true
enableRobotsTXT = true

[sitemap]
  changefreq = 'monthly'

[params]
  repo = "https://github.com/klausbreyer/v01.io/blob/main/content/"

[menu]
# [[menu.main]]
#   name = 'Open Source'
#   url = '/categories/open-source/'
#   weight = 100

# [[menu.main]]
#   name = 'unixtime.app'
#   url = '/categories/unixtime.app/'
#   weight = 110

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
